### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by YES-Lee** [BinChengZhao/delicate#13]
Need a guidelines for contribution。

**Comment by nelsonkimani63** [comment]
Hi @YES-Lee,

Is this still open? I'll be glad to work on it. Thanks

**Comment by BinChengZhao** [comment]
Hi friends @YES-Lee  @nelsonkimani63 , the contributor guide is now complete, if you have any questions please reply to me in the issue, I appreciate your support.

[contribution-guide](https://github.com/BinChengZhao/delicate#Contributing)
