### ISSUE TITLE
delay_timer-0.9.2/src/utils/parse.rs build error

### ISSUE THREAD

**Issue by liyunde** [BinChengZhao/delicate#34]
- Rust: [1.58.1]
 - OS: [centos8]
 - Version [main]

**Additional context**

delay_timer-0.9.2/src/utils/parse.rs:308:9
    |
308 |         Ok(process_linked_list)
    |         ^^^^^^^^^^^^^^^^^^^^^^^ expected enum `error::CommandChildError`, found struct `anyhow::Error`

**Comment by BinChengZhao** [comment]
> 

Thank you for your feedback, I will follow up with the version upgrade

**Comment by BinChengZhao** [comment]
> liyunde

@liyunde  Hi friends it is already fixed ~

Thank you for your feedback :)
